### Nominal Encoding (OneHotEncoding)

In [3]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

df = pd.DataFrame({
    "colors" : ["Red", "Blue", "Green", "Green", "Blue", "Red", "Green"]
})

encoder = OneHotEncoder()

encoder.fit_transform(df[['colors']]).toarray()

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.]])

In [4]:
## for other data

encoder.transform([["Blue"], ["Red"]]).toarray()

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[1., 0., 0.],
       [0., 0., 1.]])

### LabelEncoding(OrdinalEncoding)

In [5]:
from  sklearn.preprocessing import LabelEncoder


label_encoder = LabelEncoder()
label_encoder.fit_transform(df[["colors"]])

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([2, 0, 1, 1, 0, 2, 1])

### Ordinal Encoding

In [6]:
from sklearn.preprocessing import OrdinalEncoder
import pandas as pd

df = pd.DataFrame({
    "size" : ["small", "medium", "large", "small", "large"]
})


ordinal_encoder = OrdinalEncoder(categories=[["small", "medium", "large"]])
ordinal_encoder.fit_transform(df)

array([[0.],
       [1.],
       [2.],
       [0.],
       [2.]])

### Target Guided Ordinal Encoding

In [7]:
import pandas as pd

df = pd.DataFrame({
    "city" : ["New York", "New Jersey", "Los Angeles", "Florida", "New Jersey", "Los Angeles"],
    "price" : [100, 200, 600, 450, 100, 300]
})
df

          city  price
0     New York    100
1   New Jersey    200
2  Los Angeles    600
3      Florida    450
4   New Jersey    100
5  Los Angeles    300

In [8]:
mean_price = df.groupby("city")["price"].mean().to_dict()

In [9]:
mean_price

{'Florida': 450.0,
 'Los Angeles': 450.0,
 'New Jersey': 150.0,
 'New York': 100.0}

In [10]:
df['city_encoded'] = df['city'].map(mean_price)

In [11]:
df

          city  price  city_encoded
0     New York    100         100.0
1   New Jersey    200         150.0
2  Los Angeles    600         450.0
3      Florida    450         450.0
4   New Jersey    100         150.0
5  Los Angeles    300         450.0

In [17]:
import seaborn as sns

tips_data = sns.load_dataset('tips')

time_encoded = tips_data.groupby('time')['total_bill'].mean().to_dict()

/var/folders/v9/w1j71nzs1hxgws4nxlscb6540000gn/T/ipykernel_92857/145514930.py:5: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  time_encoded = tips_data.groupby('time')['total_bill'].mean().to_dict()

In [18]:
tips_data['time_encoded'] = tips_data['time'].map(time_encoded)

In [20]:
tips_data

     total_bill   tip     sex smoker   day    time  size time_encoded
0         16.99  1.01  Female     No   Sun  Dinner     2    20.797159
1         10.34  1.66    Male     No   Sun  Dinner     3    20.797159
2         21.01  3.50    Male     No   Sun  Dinner     3    20.797159
3         23.68  3.31    Male     No   Sun  Dinner     2    20.797159
4         24.59  3.61  Female     No   Sun  Dinner     4    20.797159
..          ...   ...     ...    ...   ...     ...   ...          ...
239       29.03  5.92    Male     No   Sat  Dinner     3    20.797159
240       27.18  2.00  Female    Yes   Sat  Dinner     2    20.797159
241       22.67  2.00    Male    Yes   Sat  Dinner     2    20.797159
242       17.82  1.75    Male     No   Sat  Dinner     2    20.797159
243       18.78  3.00  Female     No  Thur  Dinner     2    20.797159

[244 rows x 8 columns]